version: 2.1

jobs:
  build:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: docker build -t myapp:latest .
      - persist_to_workspace:
          root: .
          paths:
            - Dockerfile
            - .circleci
  run_container:
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Run Docker container
          command: docker run -d -p 8080:8080 --name myapp_container myapp:latest
  push_to_dockerhub:
    docker:
      - image: circleci/node:14
    steps:
      - attach_workspace:
          at: .
      - setup_remote_docker
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Tag Docker image
          command: docker tag myapp:latest $DOCKERHUB_USERNAME/myapp:latest
      - run:
          name: Push Docker image to Docker Hub
          command: docker push $DOCKERHUB_USERNAME/myapp:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - run_container:
          requires:
            - build
      - push_to_dockerhub:
          requires:
            - run_container