version: 2.1

executors:
  node-executor:
    docker:
      - image: circleci/node:14
    working_directory: ~/repo

jobs:
  build:
    executor: node-executor
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - setup_remote_docker:
          version: 20.10.7
      - run:
          name: Build Docker image
          command: docker build -t myapp:latest .
      - run:
          name: Run Docker container
          command: docker run -d -p 8080:8080 --name myapp_container myapp:latest
      - run:
          name: Check if port 8080 is reachable
          command: |
            sleep 10
            curl --fail http://localhost:8080 || (docker logs myapp_container && exit 1)
      - run:
          name: Login to Docker Hub
          command: |
            echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
      - run:
          name: Tag Docker image
          command: docker tag myapp:latest $DOCKERHUB_USERNAME/myapp:latest
      - run:
          name: Push Docker image to Docker Hub
          command: docker push $DOCKERHUB_USERNAME/myapp:latest

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build